apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prabhuvamsi98/git-practice.git
    targetRevision: master
    path: mychart

  destination:
    server: https://kubernetes.default.svc
    namespace: helm-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
